### PR TITLE
Feature: support excluding cameras

### PR DESCRIPTION
**Pull request by boakham**
Please allow excluding of cameras (based on uuid rather than serial no since they don't seem to have a serial no here) the same way we can exclude other devices.

### CODE REVIEW

**Comment by shamoon** [comment]
You can usually get the serial from the web app settings > devices. The mobile app also shows the serial under the camera settings > basic info

**Comment by shamoon** [comment]
Yes, I know that, but Im saying we should still use the serial which users can get easily rather than the uuid.

**Comment by boakham** [comment]
Oh I see! The reason I used uuid is because the Camera class does not include a serial no property, and I don't know if the SimpliSafe api returns those for cameras. Everything in the Camera class is driven by uuid, so I was being consistent with that.

**Comment by shamoon** [comment]
It’ll be in there somewhere. I think more important is to make it easier for users than code ‘consistency’. I’ll have a look later when I have some time. Thanks for the PR

**Comment by boakham** [comment]
It works! Thank you!

**Pull request merged**
